

import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'zh-CN' | 'zh-TW' | 'ru';

export const translations = {
  en: {
    groupEnterprise: 'Enterprise',
    groupWorkforce: 'Workforce',
    groupFinancials: 'Financials',
    groupSystem: 'System',

    // Menu Items
    dashboard: 'Dashboard',
    companyInfo: 'Enterprise Info',
    accountTopUp: 'Account Top-up',
    entContracts: 'Ent. Contracts',
    
    employees: 'Employee List',
    empTags: 'Team Tags',
    empContracts: 'Emp. Contracts',
    
    payroll: 'Global Payroll',
    reimbursements: 'Reimbursements',
    socialSecurity: 'Social Security',
    
    securitySettings: 'Security Settings',
    logout: 'Log out',
    
    // Enterprise Contracts
    contractsOverview: 'Manage your master service agreements and legal documents.',
    contractsActive: 'Active Contracts',
    contractsPending: 'Pending Signature',
    contractsExpiring: 'Expiring Soon',
    contractName: 'Contract Name',
    contractType: 'Type',
    effectiveDate: 'Effective Date',
    contractStatus: 'Status',
    contractActions: 'Actions',
    signContract: 'Sign Contract',
    downloadPdf: 'Download PDF',
    viewContract: 'View Contract',
    signedOn: 'Signed on',
    contractId: 'Contract ID',
    
    typeMSA: 'Master Services Agreement',
    typeNDA: 'Non-Disclosure Agreement',
    typeDPA: 'Data Processing Agreement',
    typeSOW: 'Statement of Work',
    statusActive: 'Active',
    statusPending: 'Pending Signature',
    statusExpired: 'Expired',
    statusDraft: 'Draft',
    
    signModalTitle: 'Sign Document',
    signModalDesc: 'Please review and sign the document electronically.',
    legalName: 'Legal Name',
    drawSignature: 'Draw Signature',
    adoptAndSign: 'Adopt & Sign',
    uploadContract: 'Upload Contract',
    
    // Expenses
    expensesOverview: 'Manage employee reimbursements and claims.',
    newExpense: 'New Reimbursement',
    totalReimbursed: 'Total Reimbursed (YTD)',
    totalReimbursedCount: 'Total Paid Claims',
    pendingApproval: 'Pending Approval',
    batchId: 'Batch ID',
    totalItems: 'Items',
    totalAmount: 'Total Amount',
    
    // Expense Wizard
    stepAddItems: '1. Add Expenses',
    stepReviewExpenses: '2. Review Batch',
    stepPayExpenses: '3. Payment',
    
    expenseCategory: 'Category',
    expenseDate: 'Date',
    expenseDesc: 'Description',
    expenseAmount: 'Amount',
    expenseCurrency: 'Currency',
    expenseAttachment: 'Receipt / Attachment',
    uploadReceipt: 'Upload Receipt',
    dragDrop: 'Drag & drop or click to upload',
    addItem: 'Add Item',
    noItemsAdded: 'No expense items added yet.',
    selectBankAccount: 'Select Bank Account',
    searchEmployee: 'Search Employee...',
    exchangeRateDisplay: 'Exchange Rate',
    convertedAmount: 'Converted Amount',
    
    catTravel: 'Travel',
    catMeals: 'Meals',
    catAccommodation: 'Accommodation',
    catOffice: 'Office Supplies',
    catTraining: 'Training',
    catOther: 'Other',

    // Login Page
    loginTitle: 'Log in to PayDD',
    loginSubtitle: 'Global payroll & compliance platform',
    emailLabel: 'Email Address',
    passwordLabel: 'Password',
    mobileLabel: 'Mobile Number',
    codeLabel: 'Verification Code',
    sendCode: 'Send Code',
    resendCode: 'Resend in {{time}}s',
    signIn: 'Sign In',
    loggingIn: 'Logging in...',
    forgotPassword: 'Forgot password?',
    noAccount: "Don't have an account?",
    contactSales: 'Contact Sales',
    welcomeBack: 'Welcome Back',
    enterEmail: 'Enter your email',
    enterPassword: 'Enter your password',
    enterMobile: 'Enter mobile number',
    enterCode: 'Enter 6-digit code',
    loginSuccess: 'Login Successful',

    // Dashboard
    dashboardOverview: 'Overview of your global workforce and payroll.',
    lastUpdated: 'Last updated',
    totalPayrollCost: 'Total Payroll Cost',
    activeEmployees: 'Active Employees',
    countriesActive: 'Countries Active',
    pendingPayments: 'Pending Payments',
    payrollHistory: 'Payroll History',
    costByCountry: 'Cost by Country',
    topMkts: 'Top Mkts',
    hireNewCountry: 'Hire in a new country?',
    hireNewCountryDesc: 'Get instant quotes and compliance checks for 160+ countries.',
    startOnboarding: 'Start Onboarding',
    bankCalendar: 'Global Bank Calendar',
    upcomingHolidays: 'Upcoming Holidays',
    
    // Employees
    manageWorkforce: 'Manage your global workforce.',
    addEmployee: 'Add Employee',
    backToEmployees: 'Back to Employees',
    onboardNewEmployee: 'Onboard New Employee',
    searchPlaceholder: 'Search by name, role or country...',
    filters: 'Filters',
    roleDept: 'Role & Dept',
    location: 'Location',
    status: 'Status',
    salary: 'Salary',
    actions: 'Actions',
    monthlyGross: 'Monthly Gross',
    typeRegular: 'Regular Employee',
    typeContractor: 'Contractor',
    salaryAmount: 'Salary Amount',
    
    // Employee Actions
    offboard: 'Offboard',
    employeeDetails: 'Employee Details',
    offboardingWizard: 'Offboarding Wizard',
    lastWorkingDay: 'Last Working Day',
    reasonForLeaving: 'Reason for Leaving',
    confirmOffboard: 'Confirm Offboarding',
    resignation: 'Resignation',
    termination: 'Termination',
    contractExpiry: 'Contract Expiry',
    cancel: 'Cancel',

    // Add Employee Wizard
    stepBasicInfo: 'Employee Info',
    stepContract: 'Contract',
    stepBank: 'Bank Info',
    stepSalaryBank: 'Salary & Bank',
    personalDetails: 'Personal Details',
    employmentDetails: 'Employment Details',
    firstName: 'First Name',
    lastName: 'Last Name',
    gender: 'Gender',
    dob: 'Date of Birth',
    nationality: 'Nationality',
    email: 'Email',
    phone: 'Phone',
    idType: 'ID Type',
    idNumber: 'ID Number',
    jobTitle: 'Job Title',
    department: 'Department',
    tags: 'Tags',
    tagsPlaceholder: 'e.g. Remote, Engineering, Senior (comma separated)',
    employmentType: 'Employment Type',
    startDate: 'Start Date',
    contractTerm: 'Contract Term',
    probationPeriod: 'Probation',
    salaryCurrency: 'Currency',
    baseSalary: 'Base Salary',
    allowance: 'Allowance',
    bonus: 'Bonus',
    totalPackage: 'Total Package',
    paymentMethod: 'Payment Method',
    bankName: 'Bank Name',
    accountNumber: 'Account Number',
    swiftCode: 'SWIFT/BIC',
    holderName: 'Account Holder',
    workScope: 'Scope of Work',
    submitEmployee: 'Complete Onboarding',
    fillInEnglish: 'Please fill in English',
    
    // Contract Preview
    contractPreview: 'Contract Preview',
    employmentAgreement: 'Employment Agreement',
    contractDesc: 'This document outlines the terms of employment.',
    partyA: 'Employer (Party A)',
    partyB: 'Employee (Party B)',
    signedBy: 'Signed by',
    contractBetween: 'Employment Contract between',
    and: 'and',
    contractDate: 'Contract Date',
    
    // Tags
    tagsOverview: 'Organize your workforce with custom tags and groups.',
    createTag: 'Create Tag',
    editTag: 'Edit Tag',
    tagName: 'Tag Name',
    tagColor: 'Tag Color',
    tagDesc: 'Description',
    tagMembers: 'Members',
    taggedEmployees: 'Employees tagged with',
    noTagsFound: 'No tags found',
    deleteTagConfirm: 'Are you sure you want to delete this tag? This action cannot be undone.',
    
    // Payroll
    reviewPayroll: 'Review and approve payroll runs across all entities.',
    reportCenter: 'Report Center',
    offCycleRun: 'New Off-Cycle Run',
    activeRuns: 'Unfinished Orders',
    history: 'History',
    totalPayroll: 'Total Payroll',
    dueDate: 'Due Date',
    viewDetails: 'View Details',
    approvePay: 'Approve & Pay',
    continue: 'Continue',
    actionRequired: 'Action Required',
    downloadAll: 'Download All Reports',
    noActiveRuns: 'No unfinished orders',
    noActiveRunsDesc: 'All payroll runs have been completed. You can start a new run anytime.',
    createRunNow: 'Create Run Now',
    confirmDelete: 'Are you sure you want to delete this draft?',
    delete: 'Delete',
    
    // Payroll Details
    runDetails: 'Run Details',
    backToDashboard: 'Back to Dashboard',
    paymentStatus: 'Payment Status',
    payNow: 'Pay Now',
    downloadInvoice: 'Download Invoice',
    downloadReport: 'Download Report',
    employeeList: 'Employee List',
    
    // Payroll Creation
    createPayrollRun: 'Create Payroll Run',
    stepSelectEmployees: '1. Select Employees',
    stepReviewDetails: '2. Review & Edit',
    stepSummary: '3. Order Summary',
    stepPayment: '4. Payment',
    selectAll: 'Select All',
    selected: 'Selected',
    nextStep: 'Next Step',
    prevStep: 'Previous',
    saveDraft: 'Save Draft',
    submitOrder: 'Proceed to Payment',
    beneficiary: 'Beneficiary',
    paymentAmount: 'Payment Amount',
    paymentCurrency: 'Currency',
    draftSaved: 'Draft saved successfully!',
    draftDesc: 'Your changes have been saved locally.',
    
    // Payroll Pagination & Filters
    allDepartments: 'All Departments',
    allCountries: 'All Countries',
    clearSelection: 'Clear Selection',
    showingRange: 'Showing {{start}}-{{end}} of {{total}}',
    selectAllResults: 'Select all {{count}} results',
    clearAll: 'Clear All',
    
    // Payroll Real-time Calc
    exchangeRate: 'Exch. Rate',
    oneUsdEquals: '1 USD ≈',
    equivUSD: 'Equiv. USD',
    serviceFeeUSD: 'Service Fee (USD)',
    totalCostUSD: 'Total Cost (USD)',
    fxRateInfo: 'Real-time FX',
    searchCurrency: 'Search Currency...',
    selectCurrency: 'Select Currency',

    // Payroll Summary
    orderDetail: 'Order Details',
    currencyBreakdown: 'Currency Breakdown',
    totalHeadcount: 'Total Headcount',
    estServiceFee: 'Platform Service Fee (USD)',
    subtotal: 'Payroll Cost (USD)',
    grandTotal: 'Total Order Amount (USD)',
    platformFeeDesc: 'Includes platform fee & FX margin',
    exchangeRateNotice: 'Settlement is in USD. Local currencies are converted based on real-time rates.',

    // Payment Page
    paymentCheckout: 'Checkout',
    selectPaymentCurrency: 'Select Payment Currency',
    checkoutPaymentMethod: 'Payment Method',
    walletBalance: 'Wallet Balance',
    cryptoPayment: 'Crypto Payment',
    bankTransfer: 'Bank Transfer',
    amountToPay: 'Total to Pay',
    availableBalance: 'Available',
    insufficientBalance: 'Insufficient Balance',
    confirmPayment: 'Confirm Payment',
    paymentSuccess: 'Payment Successful!',
    paymentSuccessDesc: 'Your payroll order has been processed.',
    returnToDashboard: 'Return to Dashboard',
    finalExchangeRate: 'Final Rate',
    cryptoProcessingFee: 'Crypto Processing Fee (0.5%)',

    // Wallet
    totalAssetsValuation: 'Total Assets Valuation',
    myAssets: 'My Assets',
    estimatedValue: 'Estimated Value',
    topUp: 'Top Up',
    fiatCurrency: 'Fiat Currency',
    cryptoCurrency: 'Crypto Currency',
    fiat: 'Fiat',
    crypto: 'Crypto',
    addAsset: 'Add Asset',
    transactionFlow: 'Transaction Flow',
    topUpRecords: 'Top-up Records',
    transactionNo: 'Transaction ID',
    transactionDate: 'Date',
    transactionType: 'Type',
    amount: 'Amount',
    balance: 'Balance',
    note: 'Note',
    fiatTopUp: 'Fiat Top-up',
    payrollPayment: 'Payroll Payment',
    refund: 'Refund',
    withdraw: 'Withdraw',
    exchange: 'Exchange',
    page: 'Page',
    
    // Top-up Details
    orderNo: 'Order No',
    topUpDate: 'Top-up Date',
    topUpStatus: 'Status',
    topUpDetails: 'Details',
    view: 'View',
    orderInfo: 'Order Information',
    bankAccountInfo: 'Beneficiary Bank Account Info',
    countryRegion: 'Country/Region',
    topUpBankName: 'Bank Name',
    bankAccountNo: 'Bank Account No.',
    bankAccountName: 'Bank Account Name',
    bankCode: 'Bank Code',
    beneficiaryAddress: 'Beneficiary Address',
    branchCode: 'Branch Code',
    topUpSwiftCode: 'SWIFT Code',
    topUpPaymentMethod: 'Payment Method',
    statusCancelled: 'Cancelled',
    statusPending: 'Pending',
    statusSuccess: 'Success',
    close: 'Close',

    // Company Info
    enterpriseInfo: 'Enterprise Information',
    enterpriseVerified: 'Enterprise Verified',
    basicInfo: 'Basic Information',
    basicInfoDesc: 'Manage company identity and registration details.',
    contactInfo: 'Contact Information',
    contactInfoDesc: 'Set up primary contact points and addresses.',
    legalDocs: 'Legal & Documents',
    legalDocsDesc: 'Upload business licenses and authorized signatures.',
    shareholderInfoDesc: 'Manage equity structure and beneficiary owners.',
    
    companyNameLocal: 'Company Name (Local)',
    companyNameEn: 'Company English Name',
    regNumber: 'Registration No.',
    regDate: 'Registration Date',
    regCountry: 'Registration Country/Region',
    companySize: 'Company Size',
    regAddress: 'Registered Address',
    regCapital: 'Registered Capital',
    entBusinessScope: 'Business Scope',
    
    website: 'Website',
    contactPerson: 'Contact Person',
    contactPhone: 'Phone Number',
    contactEmail: 'Email',
    contactAddress: 'Contact Address',
    companyIntro: 'Company Introduction',
    
    companySeal: 'Company Seal',
    businessLicense: 'Business License',
    authSignatoryName: 'Authorized Signatory Name',
    authSignatorySign: 'Authorized Signatory Signature',
    sign: 'Sign',
    
    save: 'Save Changes',
    next: 'Next Step',
    previous: 'Previous',
    profileCompletion: 'Profile Completion',
    
    shareholderInfo: 'Shareholders',
    entityType: 'Entity Type',
    personType: 'Person Type',
    shareholderName: 'Shareholder Name',
    shareholderIdNumber: 'ID/Reg No.',
    shareholderIdType: 'ID Type',
    mobile: 'Mobile',
    refresh: 'Refresh',
    edit: 'Edit',
    
    // AI Copilot
    copilotWelcome: 'Hello! I am your PayDD Compliance Copilot. Ask me about labor laws, payroll regulations, or hiring in new countries.',
    copilotPlaceholder: 'Ask about compliance, taxes...',
    aiDisclaimer: 'AI can make mistakes. Verify critical compliance info.',
    copilotTitle: 'PayDD Copilot',
    
    // Common
    search: 'Search...',
    headerSlogan: 'Global Payroll & Compliance Platform',
  },
  'zh-CN': {
    groupEnterprise: '企业管理',
    groupWorkforce: '员工管理',
    groupFinancials: '财务服务',
    groupSystem: '系统设置',

    dashboard: '工作台',
    companyInfo: '企业信息',
    accountTopUp: '账户充值',
    entContracts: '企业合同',
    
    employees: '员工列表',
    empTags: '团队标签',
    empContracts: '员工合同',
    
    payroll: '全球薪酬',
    reimbursements: '费用报销',
    socialSecurity: '社保发放',
    
    securitySettings: '安全设置',
    logout: '退出登录',
    
    // Enterprise Contracts
    contractsOverview: '管理您的主服务协议和法律文件。',
    contractsActive: '生效中',
    contractsPending: '待签署',
    contractsExpiring: '即将过期',
    contractName: '合同名称',
    contractType: '类型',
    effectiveDate: '生效日期',
    contractStatus: '状态',
    contractActions: '操作',
    signContract: '签署合同',
    downloadPdf: '下载 PDF',
    viewContract: '查看合同',
    signedOn: '签署于',
    contractId: '合同编号',
    
    typeMSA: '主服务协议 (MSA)',
    typeNDA: '保密协议 (NDA)',
    typeDPA: '数据处理协议 (DPA)',
    typeSOW: '工作说明书 (SOW)',
    statusActive: '生效中',
    statusPending: '待签署',
    statusExpired: '已过期',
    statusDraft: '草稿',
    
    signModalTitle: '签署文件',
    signModalDesc: '请查阅并电子签署文件。',
    legalName: '法定姓名',
    drawSignature: '绘制签名',
    adoptAndSign: '确认并签署',
    uploadContract: '上传合同',

    // Expenses
    expensesOverview: '管理员工报销和费用申请。',
    newExpense: '新增报销',
    totalReimbursed: '已报销总额',
    totalReimbursedCount: '已报销总笔数',
    pendingApproval: '待审批',
    batchId: '批次 ID',
    totalItems: '条目数',
    totalAmount: '总金额',

    // Expense Wizard
    stepAddItems: '1. 添加费用',
    stepReviewExpenses: '2. 确认批次',
    stepPayExpenses: '3. 支付',

    expenseCategory: '费用类型',
    expenseDate: '发生日期',
    expenseDesc: '费用描述',
    expenseAmount: '金额',
    expenseCurrency: '币种',
    expenseAttachment: '凭证 / 附件',
    uploadReceipt: '上传凭证',
    dragDrop: '拖拽或点击上传文件',
    addItem: '添加费用',
    noItemsAdded: '暂无费用条目。',
    selectBankAccount: '选择收款账户',
    searchEmployee: '搜索员工...',
    exchangeRateDisplay: '参考汇率',
    convertedAmount: '折算金额',

    catTravel: '差旅交通',
    catMeals: '餐饮',
    catAccommodation: '住宿',
    catOffice: '办公用品',
    catTraining: '培训',
    catOther: '其他',

    // Login Page
    loginTitle: '登录 PayDD',
    loginSubtitle: '全球薪酬与合规平台',
    emailLabel: '电子邮箱',
    passwordLabel: '密码',
    mobileLabel: '手机号码',
    codeLabel: '验证码',
    sendCode: '获取验证码',
    resendCode: '重新发送 ({{time}}s)',
    signIn: '登录',
    loggingIn: '登录中...',
    forgotPassword: '忘记密码？',
    noAccount: "还没有账号？",
    contactSales: '联系销售',
    welcomeBack: '欢迎回来',
    enterEmail: '请输入邮箱',
    enterPassword: '请输入密码',
    enterMobile: '请输入手机号',
    enterCode: '请输入6位验证码',
    loginSuccess: '登录成功',

    dashboardOverview: '全球员工和薪酬概览。',
    lastUpdated: '最后更新',
    totalPayrollCost: '薪酬总成本',
    activeEmployees: '在职员工',
    countriesActive: '覆盖国家',
    pendingPayments: '待处理款项',
    payrollHistory: '薪酬历史',
    costByCountry: '成本分布 (按国家)',
    topMkts: '主要市场',
    hireNewCountry: '在新的国家招聘？',
    hireNewCountryDesc: '获取全球 160+ 个国家的即时报价和合规检查。',
    startOnboarding: '开始入职',
    bankCalendar: '全球银行日历',
    upcomingHolidays: '即将到来的假期',

    manageWorkforce: '管理您的全球员工队伍。',
    addEmployee: '添加员工',
    backToEmployees: '返回员工列表',
    onboardNewEmployee: '入职新员工',
    searchPlaceholder: '按姓名、职位或国家搜索...',
    filters: '筛选',
    roleDept: '职位 & 部门',
    location: '地点',
    status: '状态',
    salary: '薪资',
    actions: '操作',
    monthlyGross: '月度总额',
    typeRegular: '正式员工',
    typeContractor: '灵活用工',
    salaryAmount: '薪资金额',

    // Employee Actions
    offboard: '离职',
    employeeDetails: '员工详情',
    offboardingWizard: '离职办理',
    lastWorkingDay: '最后工作日',
    reasonForLeaving: '离职原因',
    confirmOffboard: '确认离职',
    resignation: '主动辞职',
    termination: '解雇',
    contractExpiry: '合同到期',
    cancel: '取消',

    // Add Employee Wizard
    stepBasicInfo: '员工信息',
    stepContract: '完善合同',
    stepBank: '银行卡信息',
    stepSalaryBank: '薪资与银行',
    personalDetails: '个人信息',
    employmentDetails: '雇佣信息',
    firstName: '名',
    lastName: '姓',
    gender: '性别',
    dob: '出生日期',
    nationality: '国家/地区',
    email: '邮箱',
    phone: '电话',
    idType: '证件类型',
    idNumber: '证件',
    jobTitle: '职位',
    department: '部门',
    tags: '标签',
    tagsPlaceholder: '例如：远程, 技术部, 資深 (逗号分隔)',
    employmentType: '雇佣类型',
    startDate: '入职日期',
    contractTerm: '合同期限',
    probationPeriod: '试用期',
    salaryCurrency: '薪资币种',
    baseSalary: '基本薪资',
    allowance: '补贴',
    bonus: '奖金',
    totalPackage: '总薪资',
    paymentMethod: '薪酬发放方式',
    bankName: '银行名称',
    accountNumber: '银行账号',
    swiftCode: 'SWIFT代码',
    holderName: '开户人姓名',
    workScope: '工作内容',
    submitEmployee: '完成入职',
    fillInEnglish: '仅限英文填写',
    
    // Contract Preview
    contractPreview: '合同预览',
    employmentAgreement: '雇佣协议',
    contractDesc: '本文件概述了雇佣条款。',
    partyA: '甲方 (雇主)',
    partyB: '乙方 (雇员)',
    signedBy: '签署人',
    contractBetween: '雇佣合同签约方：',
    and: '与',
    contractDate: '签约日期',

    // Tags
    tagsOverview: '使用自定义标签和群组来组织您的员工队伍。',
    createTag: '创建标签',
    editTag: '编辑标签',
    tagName: '标签名称',
    tagColor: '标签颜色',
    tagDesc: '描述',
    tagMembers: '成员',
    taggedEmployees: '属于该标签的员工',
    noTagsFound: '未找到标签',
    deleteTagConfirm: '确定要删除此标签吗？此操作无法撤销。',

    reviewPayroll: '审核并批准所有实体的薪酬运行。',
    reportCenter: '报表中心',
    offCycleRun: '新增发薪订单',
    activeRuns: '未完成订单',
    history: '历史记录',
    totalPayroll: '薪酬总额',
    dueDate: '截止日期',
    viewDetails: '查看详情',
    approvePay: '批准并支付',
    continue: '继续',
    actionRequired: '需要操作',
    downloadAll: '下载所有报表',
    noActiveRuns: '暂无未完成订单',
    noActiveRunsDesc: '当前没有待处理的发薪订单，您可以随时创建新的发薪流程。',
    createRunNow: '立即创建',
    confirmDelete: '确定要删除此草稿订单吗？',
    delete: '删除',

    // Payroll Details
    runDetails: '订单详情',
    backToDashboard: '返回列表',
    paymentStatus: '支付状态',
    payNow: '立即支付',
    downloadInvoice: '下载发票',
    downloadReport: '下载报表',
    employeeList: '发薪名单',

    // Payroll Creation
    createPayrollRun: '创建发薪订单',
    stepSelectEmployees: '1. 选择员工',
    stepReviewDetails: '2. 确认详情',
    stepSummary: '3. 订单汇总',
    stepPayment: '4. 支付收银台',
    selectAll: '全选',
    selected: '已选择',
    nextStep: '下一步',
    prevStep: '上一步',
    saveDraft: '保存草稿',
    submitOrder: '前往支付',
    beneficiary: '收款账户',
    paymentAmount: '实发金额',
    paymentCurrency: '发放币种',
    draftSaved: '草稿已保存！',
    draftDesc: '您的发薪信息已保存至本地。',
    
    // Payroll Pagination & Filters
    allDepartments: '所有部门',
    allCountries: '所有国家',
    clearSelection: '清空选择',
    showingRange: '显示 {{start}}-{{end}} / 共 {{total}}',
    selectAllResults: '选择所有 {{count}} 个结果',
    clearAll: '清空',

    // Payroll Real-time Calc
    exchangeRate: '汇率',
    oneUsdEquals: '1 USD ≈',
    equivUSD: '折合 USD',
    serviceFeeUSD: '服务费 (USD)',
    totalCostUSD: '总成本 (USD)',
    fxRateInfo: '实时汇率',
    searchCurrency: '搜索币种...',
    selectCurrency: '选择币种',

    // Payroll Summary
    orderDetail: '订单明细',
    currencyBreakdown: '币种明细',
    totalHeadcount: '总人数',
    estServiceFee: '平台服务费 (USD)',
    subtotal: '薪资成本 (USD)',
    grandTotal: '订单总额 (USD)',
    platformFeeDesc: '包含平台服务费及汇率损耗',
    exchangeRateNotice: '订单以美元结算。本地货币金额已按实时汇率折算为美元。',

    // Payment Page
    paymentCheckout: '收银台',
    selectPaymentCurrency: '选择支付币种',
    checkoutPaymentMethod: '支付方式',
    walletBalance: '钱包余额',
    cryptoPayment: '加密货币支付',
    bankTransfer: '银行转账',
    amountToPay: '用户实付金额',
    availableBalance: '可用余额',
    insufficientBalance: '余额不足',
    confirmPayment: '确认支付',
    paymentSuccess: '支付成功！',
    paymentSuccessDesc: '您的发薪订单已处理完毕。',
    returnToDashboard: '返回工作台',
    finalExchangeRate: '结算汇率',
    cryptoProcessingFee: '加密货币支付手续费 (0.5%)',

    // Wallet
    totalAssetsValuation: '总资产估值',
    myAssets: '我的资产',
    estimatedValue: '估值',
    topUp: '充值',
    fiatCurrency: '法定货币',
    cryptoCurrency: '加密货币',
    fiat: '法币',
    crypto: '加密货币',
    addAsset: '添加资产',
    transactionFlow: '交易流水',
    topUpRecords: '充值记录',
    transactionNo: '交易流水号',
    transactionDate: '交易日期',
    transactionType: '交易类型',
    amount: '金额',
    balance: '余额',
    note: '备注',
    fiatTopUp: '法币充值',
    payrollPayment: '薪酬代发退款',
    refund: '薪酬支付',
    withdraw: '提现',
    exchange: '换汇',
    page: '页',

    // Top-up Details
    orderNo: '充值订单号',
    topUpDate: '充值日期',
    topUpStatus: '状态',
    topUpDetails: '充值详情',
    view: '查看',
    orderInfo: '订单信息',
    bankAccountInfo: '汇款银行账户信息',
    countryRegion: '所属国家/地区',
    topUpBankName: '银行名称',
    bankAccountNo: '银行账户号',
    bankAccountName: '银行账户名',
    bankCode: '银行行号',
    beneficiaryAddress: '收款行地址',
    branchCode: '分行行号',
    topUpSwiftCode: 'SWIFT代码',
    topUpPaymentMethod: '收款方式',
    statusCancelled: '已取消',
    statusPending: '待处理',
    statusSuccess: '充值成功',
    close: '关闭',

    enterpriseInfo: '企业信息',
    enterpriseVerified: '企业已认证',
    basicInfo: '基础信息',
    basicInfoDesc: '管理企业身份和注册详情。',
    contactInfo: '联系信息',
    contactInfoDesc: '设置主要联系人和地址。',
    legalDocs: '法务与文件',
    legalDocsDesc: '上传营业执照和授权签名。',
    shareholderInfoDesc: '管理股权结构和受益所有人。',

    companyNameLocal: '企业名称 (本地)',
    companyNameEn: '企业英文名称',
    regNumber: '企业注册号',
    regDate: '企业注册日期',
    regCountry: '注册国家/地区',
    companySize: '企业规模',
    regAddress: '注册地址',
    regCapital: '注册资金',
    entBusinessScope: '业务范围',
    
    website: '公司网站',
    contactPerson: '联系人',
    contactPhone: '联系电话',
    contactEmail: '联系邮件',
    contactAddress: '联系地址',
    companyIntro: '公司介绍',
    
    companySeal: '企业公章',
    businessLicense: '营业执照或注册文件信息',
    authSignatoryName: '授权签署人姓名',
    authSignatorySign: '授权签署人签名',
    sign: '签名',
    
    save: '保存更改',
    next: '下一步',
    previous: '上一步',
    profileCompletion: '资料完善度',
    
    shareholderInfo: '股东信息',
    entityType: '实体类型',
    personType: '人员类型',
    shareholderName: '股东名称',
    shareholderIdNumber: '证件号码/企业注册号/税号',
    shareholderIdType: '证件类型',
    mobile: '手机号',
    refresh: '刷新',
    edit: '修改',

    copilotWelcome: '您好！我是 PayDD 合规助手。您可以向我咨询有关劳动法、薪酬法规或在新国家招聘的问题。',
    copilotPlaceholder: '询问合规性、税收...',
    aiDisclaimer: 'AI 可能会犯错。请核实关键合规信息。',
    copilotTitle: 'PayDD 助手',

    search: '搜索...',
    headerSlogan: '全球薪酬与合规平台',
  },
  'zh-TW': {
    groupEnterprise: '企業管理',
    groupWorkforce: '員工管理',
    groupFinancials: '財務服務',
    groupSystem: '系統設置',

    dashboard: '工作台',
    companyInfo: '企業信息',
    accountTopUp: '賬戶充值',
    entContracts: '企業合同',
    
    employees: '員工列表',
    empTags: '團隊標籤',
    empContracts: '員工合同',
    
    payroll: '全球薪酬',
    reimbursements: '費用報銷',
    socialSecurity: '社保發放',
    
    securitySettings: '安全設置',
    logout: '登出',
    
    // Enterprise Contracts
    contractsOverview: '管理您的主服務協議和法律文件。',
    contractsActive: '生效中',
    contractsPending: '待簽署',
    contractsExpiring: '即將過期',
    contractName: '合同名稱',
    contractType: '類型',
    effectiveDate: '生效日期',
    contractStatus: '狀態',
    contractActions: '操作',
    signContract: '簽署合同',
    downloadPdf: '下載 PDF',
    viewContract: '查看合同',
    signedOn: '簽署於',
    contractId: '合同編號',
    
    typeMSA: '主服務協議 (MSA)',
    typeNDA: '保密協議 (NDA)',
    typeDPA: '數據處理協議 (DPA)',
    typeSOW: '工作說明書 (SOW)',
    statusActive: '生效中',
    statusPending: '待簽署',
    statusExpired: '已過期',
    statusDraft: '草稿',
    
    signModalTitle: '簽署文件',
    signModalDesc: '請查閱並電子簽署文件。',
    legalName: '法定姓名',
    drawSignature: '繪製簽名',
    adoptAndSign: '確認並簽署',
    uploadContract: '上傳合同',

    // Expenses
    expensesOverview: '管理員工報銷和費用申請。',
    newExpense: '新增報銷',
    totalReimbursed: '已報銷總額',
    totalReimbursedCount: '已報銷總筆數',
    pendingApproval: '待審批',
    batchId: '批次 ID',
    totalItems: '條目數',
    totalAmount: '總金額',
    
    // Expense Wizard
    stepAddItems: '1. 添加費用',
    stepReviewExpenses: '2. 確認批次',
    stepPayExpenses: '3. 支付',

    expenseCategory: '費用類型',
    expenseDate: '發生日期',
    expenseDesc: '費用描述',
    expenseAmount: '金額',
    expenseCurrency: '幣種',
    expenseAttachment: '憑證 / 附件',
    uploadReceipt: '上傳憑證',
    dragDrop: '拖拽或點擊上傳文件',
    addItem: '添加費用',
    noItemsAdded: '暫無費用條目。',
    selectBankAccount: '選擇收款賬戶',
    searchEmployee: '搜索員工...',
    exchangeRateDisplay: '參考匯率',
    convertedAmount: '折算金額',

    catTravel: '差旅交通',
    catMeals: '餐飲',
    catAccommodation: '住宿',
    catOffice: '辦公用品',
    catTraining: '培訓',
    catOther: '其他',

    // Login Page
    loginTitle: '登錄 PayDD',
    loginSubtitle: '全球薪酬與合規平台',
    emailLabel: '電子郵箱',
    passwordLabel: '密碼',
    mobileLabel: '手機號碼',
    codeLabel: '驗證碼',
    sendCode: '獲取驗證碼',
    resendCode: '重新發送 ({{time}}s)',
    signIn: '登錄',
    loggingIn: '登錄中...',
    forgotPassword: '忘記密碼？',
    noAccount: "還沒有賬號？",
    contactSales: '聯繫銷售',
    welcomeBack: '歡迎回來',
    enterEmail: '請輸入郵箱',
    enterPassword: '請輸入密碼',
    enterMobile: '請輸入手機號',
    enterCode: '請輸入6位驗證碼',
    loginSuccess: '登錄成功',

    dashboardOverview: '全球員工和薪酬概覽。',
    lastUpdated: '最後更新',
    totalPayrollCost: '薪酬總成本',
    activeEmployees: '在職員工',
    countriesActive: '覆蓋國家',
    pendingPayments: '待處理款項',
    payrollHistory: '薪酬歷史',
    costByCountry: '成本分佈 (按國家)',
    topMkts: '主要市場',
    hireNewCountry: '在新的國家招聘？',
    hireNewCountryDesc: '獲取全球 160+ 個國家的即時報價和合規檢查。',
    startOnboarding: '開始入職',
    bankCalendar: '全球銀行日曆',
    upcomingHolidays: '即將到來的假期',

    manageWorkforce: '管理您的全球員工隊伍。',
    addEmployee: '添加員工',
    backToEmployees: '返回員工列表',
    onboardNewEmployee: '入職新員工',
    searchPlaceholder: '按姓名、職位或國家搜索...',
    filters: '篩選',
    roleDept: '職位 & 部門',
    location: '地點',
    status: '狀態',
    salary: '薪資',
    actions: '操作',
    monthlyGross: '月度總額',
    typeRegular: '正式員工',
    typeContractor: '靈活用工',
    salaryAmount: '薪資金額',

    // Employee Actions
    offboard: '離職',
    employeeDetails: '員工詳情',
    offboardingWizard: '離職辦理',
    lastWorkingDay: '最後工作日',
    reasonForLeaving: '離職原因',
    confirmOffboard: '確認離職',
    resignation: '主動辭職',
    termination: '解雇',
    contractExpiry: '合同到期',
    cancel: '取消',

    // Add Employee Wizard
    stepBasicInfo: '員工信息',
    stepContract: '完善合同',
    stepBank: '銀行卡信息',
    stepSalaryBank: '薪資與銀行',
    personalDetails: '個人信息',
    employmentDetails: '僱傭信息',
    firstName: '名',
    lastName: '姓',
    gender: '性別',
    dob: '出生日期',
    nationality: '國家/地區',
    email: '郵箱',
    phone: '電話',
    idType: '證件類型',
    idNumber: '證件',
    jobTitle: '職位',
    department: '部門',
    tags: '標籤',
    tagsPlaceholder: '例如：遠程, 技術部, 資深 (逗號分隔)',
    employmentType: '雇傭類型',
    startDate: '入職日期',
    contractTerm: '合同期限',
    probationPeriod: '試用期',
    salaryCurrency: '薪資幣種',
    baseSalary: '基本薪資',
    allowance: '補貼',
    bonus: '獎金',
    totalPackage: '總薪資',
    paymentMethod: '薪酬發放方式',
    bankName: '銀行名稱',
    accountNumber: '銀行賬號',
    swiftCode: 'SWIFT代碼',
    holderName: '開戶人姓名',
    workScope: '工作內容',
    submitEmployee: '完成入職',
    fillInEnglish: '僅限英文填寫',
    
    // Contract Preview
    contractPreview: '合同預覽',
    employmentAgreement: '雇傭協議',
    contractDesc: '本文件概述了雇傭條款。',
    partyA: '甲方 (雇主)',
    partyB: '乙方 (雇員)',
    signedBy: '簽署人',
    contractBetween: '僱傭合約簽約方：',
    and: '與',
    contractDate: '簽約日期',

    // Tags
    tagsOverview: '使用自定義標籤和群組來組織您的員工隊伍。',
    createTag: '創建標籤',
    editTag: '編輯標籤',
    tagName: '標籤名稱',
    tagColor: '標籤顏色',
    tagDesc: '描述',
    tagMembers: '成員',
    taggedEmployees: '屬於該標籤的員工',
    noTagsFound: '未找到標籤',
    deleteTagConfirm: '確定要刪除此標籤嗎？此操作無法撤銷。',

    reviewPayroll: '審核並批准所有實體的薪酬運行。',
    reportCenter: '報表中心',
    offCycleRun: '新增發薪訂單',
    activeRuns: '未完成訂單',
    history: '歷史記錄',
    totalPayroll: '薪酬總額',
    dueDate: '截止日期',
    viewDetails: '查看詳情',
    approvePay: '批准並支付',
    continue: '繼續',
    actionRequired: '需要操作',
    downloadAll: '下載所有報表',
    noActiveRuns: '暫無未完成訂單',
    noActiveRunsDesc: '當前沒有待處理的發薪訂單，您可以隨時創建新的發薪流程。',
    createRunNow: '立即創建',
    confirmDelete: '確定要刪除此草稿訂單嗎？',
    delete: '刪除',

    // Payroll Details
    runDetails: '訂單詳情',
    backToDashboard: '返回列表',
    paymentStatus: '支付狀態',
    payNow: '立即支付',
    downloadInvoice: '下載發票',
    downloadReport: '下載報表',
    employeeList: '發薪名單',

    // Payroll Creation
    createPayrollRun: '創建發薪訂單',
    stepSelectEmployees: '1. 選擇員工',
    stepReviewDetails: '2. 確認詳情',
    stepSummary: '3. 訂單匯總',
    stepPayment: '4. 支付收銀台',
    selectAll: '全選',
    selected: '已選擇',
    nextStep: '下一步',
    prevStep: '上一步',
    saveDraft: '保存草稿',
    submitOrder: '前往支付',
    beneficiary: '收款賬戶',
    paymentAmount: '實發金額',
    paymentCurrency: '發放幣種',
    draftSaved: '草稿已保存！',
    draftDesc: '您的發薪信息已保存至本地。',
    
    // Payroll Pagination & Filters
    allDepartments: '所有部門',
    allCountries: '所有國家',
    clearSelection: '清空選擇',
    showingRange: '顯示 {{start}}-{{end}} / 共 {{total}}',
    selectAllResults: '選擇所有 {{count}} 個結果',
    clearAll: '清空',

    // Payroll Real-time Calc
    exchangeRate: '匯率',
    oneUsdEquals: '1 USD ≈',
    equivUSD: '折合 USD',
    serviceFeeUSD: '服務費 (USD)',
    totalCostUSD: '總成本 (USD)',
    fxRateInfo: '實時匯率',
    searchCurrency: '搜索幣種...',
    selectCurrency: '選擇幣種',

    // Payroll Summary
    orderDetail: '訂單明細',
    currencyBreakdown: '幣種明細',
    totalHeadcount: '總人數',
    estServiceFee: '平台服務費 (USD)',
    subtotal: '薪資成本 (USD)',
    grandTotal: '訂單總額 (USD)',
    platformFeeDesc: '包含平台服務費及匯率損耗',
    exchangeRateNotice: '訂單以美元結算。本地貨幣金額已按實時匯率折算為美元。',

    // Payment Page
    paymentCheckout: '收銀台',
    selectPaymentCurrency: '選擇支付幣種',
    checkoutPaymentMethod: '支付方式',
    walletBalance: '錢包餘額',
    cryptoPayment: '加密貨幣支付',
    bankTransfer: '銀行轉賬',
    amountToPay: '用戶實付金額',
    availableBalance: '可用餘額',
    insufficientBalance: '餘額不足',
    confirmPayment: '確認支付',
    paymentSuccess: '支付成功！',
    paymentSuccessDesc: '您的發薪訂單已處理完畢。',
    returnToDashboard: '返回工作台',
    finalExchangeRate: '結算匯率',
    cryptoProcessingFee: '加密貨幣支付手續費 (0.5%)',

    // Wallet
    totalAssetsValuation: '總資產估值',
    myAssets: '我的資產',
    estimatedValue: '估值',
    topUp: '充值',
    fiatCurrency: '法定貨幣',
    cryptoCurrency: '加密貨幣',
    fiat: '法幣',
    crypto: '加密貨幣',
    addAsset: '添加資產',
    transactionFlow: '交易流水',
    topUpRecords: '充值記錄',
    transactionNo: '交易流水號',
    transactionDate: '交易日期',
    transactionType: '交易類型',
    amount: '金額',
    balance: '餘額',
    note: '備註',
    fiatTopUp: '法幣充值',
    payrollPayment: '薪酬代發退款',
    refund: '薪酬支付',
    withdraw: '提現',
    exchange: '換匯',
    page: '頁',

    // Top-up Details
    orderNo: '充值訂單號',
    topUpDate: '充值日期',
    topUpStatus: '狀態',
    topUpDetails: '充值詳情',
    view: '查看',
    orderInfo: '訂單信息',
    bankAccountInfo: '匯款銀行賬戶信息',
    countryRegion: '所屬國家/地區',
    topUpBankName: '銀行名稱',
    bankAccountNo: '銀行賬戶號',
    bankAccountName: '銀行賬戶名',
    bankCode: '銀行行號',
    beneficiaryAddress: '收款行地址',
    branchCode: '分行行號',
    topUpSwiftCode: 'SWIFT代碼',
    topUpPaymentMethod: '收款方式',
    statusCancelled: '已取消',
    statusPending: '待處理',
    statusSuccess: '充值成功',
    close: '關閉',

    enterpriseInfo: '企業信息',
    enterpriseVerified: '企業已認證',
    basicInfo: '基礎信息',
    basicInfoDesc: '管理企業身份和註冊詳情。',
    contactInfo: '聯繫信息',
    contactInfoDesc: '設置主要聯繫人和地址。',
    legalDocs: '法務與文件',
    legalDocsDesc: '上傳營業執照和授權簽名。',
    shareholderInfoDesc: '管理股權結構和受益所有人。',

    companyNameLocal: '企業名稱 (本地)',
    companyNameEn: '企業英文名稱',
    regNumber: '企業註冊號',
    regDate: '企業註冊日期',
    regCountry: '註冊國家/地區',
    companySize: '企業規模',
    regAddress: '註冊地址',
    regCapital: '註冊資金',
    entBusinessScope: '業務範圍',
    
    website: '公司網站',
    contactPerson: '聯繫人',
    contactPhone: '聯繫電話',
    contactEmail: '聯繫郵件',
    contactAddress: '聯繫地址',
    companyIntro: '公司介紹',
    
    companySeal: '企業公章',
    businessLicense: '營業執照或註冊文件信息',
    authSignatoryName: '授權簽署人姓名',
    authSignatorySign: '授權簽署人簽名',
    sign: '簽名',
    
    save: '保存更改',
    next: '下一步',
    previous: '上一步',
    profileCompletion: '資料完善度',
    
    shareholderInfo: '股東信息',
    entityType: '實體類型',
    personType: '人員類型',
    shareholderName: '股東名稱',
    shareholderIdNumber: '證件號碼/企業註冊號/稅號',
    shareholderIdType: '證件類型',
    mobile: '手機號',
    refresh: '刷新',
    edit: '修改',

    copilotWelcome: '您好！我是 PayDD 合規助手。您可以向我諮詢有關勞動法、薪酬法規或在新國家招聘的問題。',
    copilotPlaceholder: '詢問合規性、稅收...',
    aiDisclaimer: 'AI 可能會犯錯。請核實關鍵合規信息。',
    copilotTitle: 'PayDD 助手',

    search: '搜索...',
    headerSlogan: '全球薪酬與合規平台',
  },
  'ru': {
    groupEnterprise: 'Управление компанией',
    groupWorkforce: 'Управление персоналом',
    groupFinancials: 'Финансы',
    groupSystem: 'Система',

    dashboard: 'Рабочий стол',
    companyInfo: 'Информация о компании',
    accountTopUp: 'Пополнение счета',
    entContracts: 'Договоры компании',
    
    employees: 'Список сотрудников',
    empTags: 'Теги сотрудников',
    empContracts: 'Договоры сотрудников',
    
    payroll: 'Глобальная зарплата',
    reimbursements: 'Возмещение расходов',
    socialSecurity: 'Соц. отчисления',
    
    securitySettings: 'Настройки безопасности',
    logout: 'Выйти',
    
    // Enterprise Contracts
    contractsOverview: 'Управление соглашениями об обслуживании и юридическими документами.',
    contractsActive: 'Активные договоры',
    contractsPending: 'Ожидают подписи',
    contractsExpiring: 'Истекают скоро',
    contractName: 'Название договора',
    contractType: 'Тип',
    effectiveDate: 'Дата вступления',
    contractStatus: 'Статус',
    contractActions: 'Действия',
    signContract: 'Подписать договор',
    downloadPdf: 'Скачать PDF',
    viewContract: 'Просмотр',
    signedOn: 'Подписано',
    contractId: 'ID договора',
    
    typeMSA: 'Генеральное соглашение (MSA)',
    typeNDA: 'Соглашение о неразглашении (NDA)',
    typeDPA: 'Соглашение об обработке данных (DPA)',
    typeSOW: 'Техническое задание (SOW)',
    statusActive: 'Активен',
    statusPending: 'Ожидает подписи',
    statusExpired: 'Истек',
    statusDraft: 'Черновик',
    
    signModalTitle: 'Подписание документа',
    signModalDesc: 'Пожалуйста, ознакомьтесь и подпишите документ.',
    legalName: 'Юридическое имя',
    drawSignature: 'Нарисовать подпись',
    adoptAndSign: 'Принять и подписать',
    uploadContract: 'Загрузить договор',

    // Expenses
    expensesOverview: 'Управление расходами и возмещениями.',
    newExpense: 'Новая заявка',
    totalReimbursed: 'Всего выплачено',
    totalReimbursedCount: 'Всего заявок',
    pendingApproval: 'Ожидает одобрения',
    batchId: 'ID партии',
    totalItems: 'Позиции',
    totalAmount: 'Сумма',
    
    // Expense Wizard
    stepAddItems: '1. Добавить расходы',
    stepReviewExpenses: '2. Проверка',
    stepPayExpenses: '3. Оплата',
    
    expenseCategory: 'Категория',
    expenseDate: 'Дата',
    expenseDesc: 'Описание',
    expenseAmount: 'Сумма',
    expenseCurrency: 'Валюта',
    expenseAttachment: 'Чек / Вложение',
    uploadReceipt: 'Загрузить чек',
    dragDrop: 'Перетащите файл или нажмите для загрузки',
    addItem: 'Добавить',
    noItemsAdded: 'Позиции пока не добавлены.',
    selectBankAccount: 'Выберите счет',
    searchEmployee: 'Поиск сотрудника...',
    exchangeRateDisplay: 'Курс обмена',
    convertedAmount: 'В USD',

    catTravel: 'Командировка',
    catMeals: 'Питание',
    catAccommodation: 'Проживание',
    catOffice: 'Офис',
    catTraining: 'Обучение',
    catOther: 'Другое',

    // Login Page
    loginTitle: 'Войти в PayDD',
    loginSubtitle: 'Глобальная платформа по расчету зарплат',
    emailLabel: 'Электронная почта',
    passwordLabel: 'Пароль',
    mobileLabel: 'Номер телефона',
    codeLabel: 'Код подтверждения',
    sendCode: 'Отправить код',
    resendCode: 'Отправить снова ({{time}}с)',
    signIn: 'Войти',
    loggingIn: 'Вход...',
    forgotPassword: 'Забыли пароль?',
    noAccount: "Нет аккаунта?",
    contactSales: 'Связаться',
    welcomeBack: 'С возвращением',
    enterEmail: 'Введите email',
    enterPassword: 'Введите пароль',
    enterMobile: 'Введите номер телефона',
    enterCode: 'Введите 6-значный код',
    loginSuccess: 'Успешный вход',

    dashboardOverview: 'Обзор глобального персонала и расчета зарплаты.',
    lastUpdated: 'Последнее обновление',
    totalPayrollCost: 'Фонд оплаты труда',
    activeEmployees: 'Активные сотрудники',
    countriesActive: 'Активные страны',
    pendingPayments: 'Ожидающие выплаты',
    payrollHistory: 'История выплат',
    costByCountry: 'Расходы по странам',
    topMkts: 'Топ рынки',
    hireNewCountry: 'Найм в новой стране?',
    hireNewCountryDesc: 'Мгновенные расчеты и проверка соответствия нормам для 160+ стран.',
    startOnboarding: 'Начать оформление',
    bankCalendar: 'Банковский календарь',
    upcomingHolidays: 'Предстоящие праздники',

    manageWorkforce: 'Управление глобальным персоналом.',
    addEmployee: 'Добавить',
    backToEmployees: 'Назад к списку',
    onboardNewEmployee: 'Новый сотрудник',
    searchPlaceholder: 'Поиск по имени, роли или стране...',
    filters: 'Фильтры',
    roleDept: 'Роль и Отдел',
    location: 'Локация',
    status: 'Статус',
    salary: 'Зарплата',
    actions: 'Действия',
    monthlyGross: 'Ежемесячный доход',
    typeRegular: 'Штатный сотрудник',
    typeContractor: 'Подрядчик',
    salaryAmount: 'Сумма зарплаты',

    // Employee Actions
    offboard: 'Уволить',
    employeeDetails: 'Детали сотрудника',
    offboardingWizard: 'Мастер увольнения',
    lastWorkingDay: 'Последний рабочий день',
    reasonForLeaving: 'Причина ухода',
    confirmOffboard: 'Подтвердить увольнение',
    resignation: 'Увольнение по собственному',
    termination: 'Расторжение контракта',
    contractExpiry: 'Окончание контракта',
    cancel: 'Отмена',

    // Add Employee Wizard
    stepBasicInfo: 'Инфо',
    stepContract: 'Контракт',
    stepBank: 'Банк',
    stepSalaryBank: 'Зарплата и Банк',
    personalDetails: 'Личные данные',
    employmentDetails: 'Служебные данные',
    firstName: 'Имя',
    lastName: 'Фамилия',
    gender: 'Пол',
    dob: 'Дата рождения',
    nationality: 'Гражданство',
    email: 'Email',
    phone: 'Телефон',
    idType: 'Тип документа',
    idNumber: 'Номер документа',
    jobTitle: 'Должность',
    department: 'Отдел',
    tags: 'Теги',
    tagsPlaceholder: 'например: Удаленно, IT, Сеньор (через запятую)',
    employmentType: 'Тип занятости',
    startDate: 'Дата начала',
    contractTerm: 'Срок контракта',
    probationPeriod: 'Испытательный срок',
    salaryCurrency: 'Валюта',
    baseSalary: 'Оклад',
    allowance: 'Надбавки',
    bonus: 'Бонус',
    totalPackage: 'Итого',
    paymentMethod: 'Способ оплаты',
    bankName: 'Банк',
    accountNumber: 'Номер счета',
    swiftCode: 'SWIFT/BIC',
    holderName: 'Владелец счета',
    workScope: 'Обязанности',
    submitEmployee: 'Завершить',
    fillInEnglish: 'Заполните на английском',
    
    // Contract Preview
    contractPreview: 'Просмотр контракта',
    employmentAgreement: 'Трудовой договор',
    contractDesc: 'В этом документе изложены условия трудоустройства.',
    partyA: 'Работодатель (Сторона А)',
    partyB: 'Работник (Сторона Б)',
    signedBy: 'Подписано',
    contractBetween: 'Трудовой договор между',
    and: 'и',
    contractDate: 'Дата контракта',
    
    // Tags
    tagsOverview: 'Организуйте персонал с помощью пользовательских тегов и групп.',
    createTag: 'Создать тег',
    editTag: 'Изменить тег',
    tagName: 'Название тега',
    tagColor: 'Цвет тега',
    tagDesc: 'Описание',
    tagMembers: 'Участники',
    taggedEmployees: 'Сотрудники с тегом',
    noTagsFound: 'Теги не найдены',
    deleteTagConfirm: 'Вы уверены, что хотите удалить этот тег? Это действие нельзя отменить.',

    reviewPayroll: 'Проверка и утверждение выплат по всем юрлицам.',
    reportCenter: 'Отчеты',
    offCycleRun: 'Внеплановый расчет',
    activeRuns: 'Незавершенные заказы',
    history: 'История',
    totalPayroll: 'Всего к выплате',
    dueDate: 'Срок',
    viewDetails: 'Подробнее',
    approvePay: 'Утвердить',
    continue: 'Продолжить',
    actionRequired: 'Требует действия',
    downloadAll: 'Скачать все отчеты',
    noActiveRuns: 'Нет незавершенных заказов',
    noActiveRunsDesc: 'Все платежные ведомости обработаны.',
    createRunNow: 'Создать заказ',
    confirmDelete: 'Вы уверены, что хотите удалить этот черновик?',
    delete: 'Удалить',

    // Payroll Details
    runDetails: 'Детали ведомости',
    backToDashboard: 'Назад',
    paymentStatus: 'Статус оплаты',
    payNow: 'Оплатить сейчас',
    downloadInvoice: 'Скачать счет',
    downloadReport: 'Скачать отчет',
    employeeList: 'Список сотрудников',

    // Payroll Creation
    createPayrollRun: 'Создать платежную ведомость',
    stepSelectEmployees: '1. Выбор сотрудников',
    stepReviewDetails: '2. Проверка и редактирование',
    stepSummary: '3. Итог',
    stepPayment: '4. Оплата',
    selectAll: 'Выбрать все',
    selected: 'Выбрано',
    nextStep: 'Далее',
    prevStep: 'Назад',
    saveDraft: 'Сохранить черновик',
    submitOrder: 'Перейти к оплате',
    beneficiary: 'Получатель',
    paymentAmount: 'Сумма выплаты',
    paymentCurrency: 'Валюта',
    draftSaved: 'Черновик сохранен!',
    draftDesc: 'Изменения сохранены локально.',

    // Payroll Pagination & Filters
    allDepartments: 'Все отделы',
    allCountries: 'Все страны',
    clearSelection: 'Очистить выбор',
    showingRange: 'Показано {{start}}-{{end}} из {{total}}',
    selectAllResults: 'Выбрать все {{count}} результатов',
    clearAll: 'Очистить',

    // Payroll Real-time Calc
    exchangeRate: 'Обменный курс',
    oneUsdEquals: '1 USD ≈',
    equivUSD: 'Экв. USD',
    serviceFeeUSD: 'Сервисный сбор (USD)',
    totalCostUSD: 'Общая стоимость (USD)',
    fxRateInfo: 'Курс в реальном времени',
    searchCurrency: 'Поиск валюты...',
    selectCurrency: 'Выберите валюту',

    // Payroll Summary
    orderDetail: 'Детали заказа',
    currencyBreakdown: 'Валюты',
    totalHeadcount: 'Всего сотрудников',
    estServiceFee: 'Сервисный сбор (USD)',
    subtotal: 'Стоимость зарплаты (USD)',
    grandTotal: 'Итоговая сумма заказа (USD)',
    platformFeeDesc: 'Включает комиссию платформы и FX',
    exchangeRateNotice: 'Расчет в USD. Местные валюты конвертируются по текущему курсу.',

    // Payment Page
    paymentCheckout: 'Касса',
    selectPaymentCurrency: 'Выберите валюту',
    checkoutPaymentMethod: 'Способ оплаты',
    walletBalance: 'Баланс кошелька',
    cryptoPayment: 'Криптовалюта',
    bankTransfer: 'Банковский перевод',
    amountToPay: 'Итого к оплате',
    availableBalance: 'Доступно',
    insufficientBalance: 'Недостаточно средств',
    confirmPayment: 'Подтвердить',
    paymentSuccess: 'Оплата прошла успешно!',
    paymentSuccessDesc: 'Ваш зарплатный заказ обработан.',
    returnToDashboard: 'Вернуться',
    finalExchangeRate: 'Итоговый курс',
    cryptoProcessingFee: 'Сбор за криптообработку (0.5%)',

    // Wallet
    totalAssetsValuation: 'Общая оценка активов',
    myAssets: 'Мои активы',
    estimatedValue: 'Оценочная стоимость',
    topUp: 'Пополнить',
    fiatCurrency: 'Фиатная валюта',
    cryptoCurrency: 'Криптовалюта',
    fiat: 'Фиат',
    crypto: 'Крипто',
    addAsset: 'Добавить актив',
    transactionFlow: 'История транзакций',
    topUpRecords: 'История пополнений',
    transactionNo: 'ID транзакции',
    transactionDate: 'Дата',
    transactionType: 'Тип',
    amount: 'Сумма',
    balance: 'Баланс',
    note: 'Примечание',
    fiatTopUp: 'Пополнение фиат',
    payrollPayment: 'Выплата зарплаты',
    refund: 'Возврат',
    withdraw: 'Вывод',
    exchange: 'Обмен',
    page: 'Стр.',

    // Top-up Details
    orderNo: '№ Ордера',
    topUpDate: 'Дата пополнения',
    topUpStatus: 'Статус',
    topUpDetails: 'Детали',
    view: 'Посмотреть',
    orderInfo: 'Информация о заказе',
    bankAccountInfo: 'Банковские реквизиты получателя',
    countryRegion: 'Страна/Регион',
    topUpBankName: 'Название банка',
    bankAccountNo: 'Номер счета',
    bankAccountName: 'Имя счета',
    bankCode: 'Код банка',
    beneficiaryAddress: 'Адрес получателя',
    branchCode: 'Код филиала',
    topUpSwiftCode: 'SWIFT код',
    topUpPaymentMethod: 'Способ оплаты',
    statusCancelled: 'Отменено',
    statusPending: 'В ожидании',
    statusSuccess: 'Успешно',
    close: 'Закрыть',

    enterpriseInfo: 'Информация о компании',
    enterpriseVerified: 'Компания верифицирована',
    basicInfo: 'Основная информация',
    basicInfoDesc: 'Управление регистрационными данными.',
    contactInfo: 'Контактная информация',
    contactInfoDesc: 'Контакты и адреса.',
    legalDocs: 'Документы',
    legalDocsDesc: 'Лицензии и подписи.',
    shareholderInfoDesc: 'Управление акционерами.',

    companyNameLocal: 'Название компании (местное)',
    companyNameEn: 'Название компании (англ.)',
    regNumber: 'Рег. номер',
    regDate: 'Дата регистрации',
    regCountry: 'Страна/регион регистрации',
    companySize: 'Размер компании',
    regAddress: 'Юридический адрес',
    regCapital: 'Уставной капитал',
    entBusinessScope: 'Сфера деятельности',
    
    website: 'Веб-сайт',
    contactPerson: 'Контактное лицо',
    contactPhone: 'Телефон',
    contactEmail: 'Email',
    contactAddress: 'Почтовый адрес',
    companyIntro: 'Описание компании',
    
    companySeal: 'Печать компании',
    businessLicense: 'Лицензия/Свидетельство',
    authSignatoryName: 'Имя подписанта',
    authSignatorySign: 'Подпись',
    sign: 'Подписать',
    
    save: 'Сохранить',
    next: 'Далее',
    previous: 'Назад',
    profileCompletion: 'Заполнение профиля',

    shareholderInfo: 'Акционеры',
    entityType: 'Тип сущности',
    personType: 'Тип лица',
    shareholderName: 'Имя акционера',
    shareholderIdNumber: 'ID/Рег. номер',
    shareholderIdType: 'Тип документа',
    mobile: 'Мобильный',
    refresh: 'Обновить',
    edit: 'Изменить',

    copilotWelcome: 'Привет! Я ваш помощник по соблюдению норм PayDD. Спрашивайте о трудовом законодательстве и налогах.',
    copilotPlaceholder: 'Спросите о налогах...',
    aiDisclaimer: 'ИИ может ошибаться. Проверяйте важную информацию.',
    copilotTitle: 'PayDD Помощник',

    search: 'Поиск...',
    headerSlogan: 'Глобальная платформа для расчета заработной платы',
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations['en'], params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: keyof typeof translations['en'], params?: Record<string, string | number>) => {
    let text = translations[language][key] || translations['en'][key] || key;
    
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{{${k}}}`, String(v));
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
